apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
data:
  APP_ENV: default  
  PORT: "8080"
  FRONTEND_BASE_URL: http://localhost:3000

  DATA_SOURCE_URL: jdbc:postgresql://user-db-service:5432/postgres
  MAIL_FROM: noreply@yourdomain.com
  MAIL_FROM_NAME: Event Platform
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"