apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    spec:
      containers: 
        - name: notification-service
          image: heahaidu/interest.notification-service