apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service-dev
  template:
    spec:
      containers: 
        - name: event-service
          image: heahaidu/interest.event-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 150m
              memory: 256Mi