apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-service-configmap
data:
  APP_ENV: default
  DATA_SOURCE_URL: jdbc:postgresql://chatbot-db-service:5432/postgres
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092