apiVersion: apps/v1
kind: Deployment
metadata: 
  name: chatbot-dev
spec: 
  replicas: 1
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector: 
    matchLabels:
      app: chatbot-dev
  template:
    metadata: 
      labels:
        app: chatbot-dev
    spec: 
      containers:
        - name: chatbot-service
          image: heahaidu/interest.chatbot-service
          ports:
            - name: http
              containerPort: 8080
      env:
        - name: DATA_SOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: chatbot-db-secret
              key: POSTGRES_DB
        - name: DATA_SOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chatbot-db-secret
              key: POSTGRES_PASSWORD
      envFrom:
        - configMapRef:
            name: chatbot-db-cm