apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-db-dev
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: notification-db-dev
  template:
    metadata:
      labels:
        app: notification-db-dev
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 192Mi
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: POSTGRES_PASSWORD
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: notification-db-pvc